### ISSUE TITLE
To_HAVE_URL in playwright doesn't expect a locator but on selecting the To_HAVE_URL function in testman it expects a locator to be provided.

### ISSUE THREAD

**Issue by Parvathi33** [testmaan/homebrew-tm#18]
**Testman :**
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/129054346/230564043-bebff972-1da4-43d8-bbbd-77478003b4c8.png">

**Playwright :**

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/129054346/230564176-52a8a651-4c09-4448-8c21-92df44b60ea0.png">

**Comment by achyuthgroot** [comment]
Details are not clear to take up the ticket. Resubmit again with proper steps & purpose.
