### ISSUE TITLE
API - request body issue.

### ISSUE THREAD

**Issue by suriya110** [testmaan/homebrew-tm#26]
While generating the request body from testman to playwright, issue occurs due to the nested request details.

Request body:
curl --location --request POST '[https://dashboard.qa.eztovrfy.com/auth/realms/automation06/protocol/openid-connect/transaction'](https://dashboard.qa.eztovrfy.com/auth/realms/automation06/protocol/openid-connect/transaction%27) \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'app_id=8765907e-14d9-485e-89b2-686627036016' \
--data-urlencode 'app_secret=AJCSDVoKcVWAJSxc4dn4fCyOBQe8jP3rFHKZZOpP3n84yMT5f4NELYyZCpFCGVGF' \
--data-urlencode 'request={
"user": {
"userId": "",
"email": "dec2026@gmail.com",
"phone": "",
"phoneRegion": "in",
"metadata": {
}
},
"message": {
"metadata": {
"pin": "123"
},
"consent":{
           "type":"string",
           "title":"Verification Request",
           "message": "Test Verification from kyc"
         }
}
}'

**Comment by NandhaSrinivasan** [comment]
The issue has been addressed in the release 1.1.0
https://github.com/testmaan/homebrew-tm/releases/tag/1.1.0
