### ISSUE TITLE
Facing difficulties using the "toBeEqual" functionality to validate API responses 

### ISSUE THREAD

**Issue by Kewin-D-chis** [testmaan/homebrew-tm#29]
Area -> Functionality 

BUG -> Couldn’t able to use toBeEqual functionality to validate API responses 

Version -> 1.1.0

Actual behaviour ->  Once the code is generated from Testman, the toBeEqual function is generated as undefined 

Steps to reproduce:

1. Use CHECK (toBeEqual) function in any of your cases and generate it
2. Now observe the behaviour in the generated code 

Expected behaviour :

The generated code should be

await expect(REST_RESPONSE@restResponse.dob).toEqual("Response value");

**Comment by NandhaSrinivasan** [comment]
Issue not reproducible
